import { chromium } from 'playwright';
const U = 'https://edinpodarak-rabotilnitsa.vercel.app';
const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage();
await p.goto(`${U}/admin/vhod`, { waitUntil: 'networkidle' });
await p.fill('#email', 'admin@example.com');
await p.fill('#password', 'rabotilnitsa');
await p.click('button[type=submit]');
await p.waitForTimeout(3000);
console.log('landed on:', p.url());
console.log('signed in:', p.url().endsWith('/admin') && !p.url().includes('vhod'));
console.log('body:', (await p.locator('body').innerText()).split('\n').filter(Boolean).slice(0, 8).join(' | '));
await b.close();
